"""Generates the system and reliability brief from an actual run.

The hackathon asks for "a short system and reliability brief". Writing one by hand
means writing claims about the system from memory, which is precisely the failure mode
this entire project argues against — so instead the brief is generated by executing the
system and reporting what happened.

Every number below is read from a live object at generation time. If the contradiction
detector stops finding the planted conflict, or the gate stops holding the customer
email, the brief says so rather than continuing to assert the good outcome. A brief
that cannot report its own failure is marketing.

    python -m walnut.brief > BRIEF.md
"""

from __future__ import annotations

import subprocess
import sys
from dataclasses import dataclass, field
from typing import Any

from .actions.executor import ActionExecutor
from .actions.governance import QueueGate, Refusal
from .adapters.fixture import load_all_fixtures, load_identities
from .agent import WalnutAgent
from .brain import Brain
from .contract import Action, ActionTier
from .contradiction import detect_contradictions

__all__ = ["Brief", "generate"]


@dataclass
class Check:
    """One claim the brief makes, and whether the run actually supports it."""

    claim: str
    passed: bool
    detail: str = ""

    def render(self) -> str:
        return f"| {'PASS' if self.passed else '**FAIL**'} | {self.claim} | {self.detail} |"


@dataclass
class Brief:
    checks: list[Check] = field(default_factory=list)
    stats: dict[str, Any] = field(default_factory=dict)
    ledger: dict[str, Any] = field(default_factory=dict)
    identities: dict[str, Any] = field(default_factory=dict)
    conflicts: int = 0
    tests: str = ""

    @property
    def all_passed(self) -> bool:
        return all(c.passed for c in self.checks)

    def render(self) -> str:
        rows = "\n".join(c.render() for c in self.checks)
        verdict = (
            "Every claim below was verified by executing the system to produce this "
            "document." if self.all_passed else
            "**One or more claims failed verification on this run. They are marked "
            "FAIL and are not corrected elsewhere in this document.**"
        )
        return f"""# Walnut — System and Reliability Brief

*Generated by `python -m walnut.brief`. Every figure is read from a live run.*

{verdict}

## What it is

A company brain over five external apps — Slack, Linear, GitHub, Notion and Email —
each connected for both read and write behind one six-method adapter contract. An agent
reasons over the resulting graph of cited facts and acts across all five, under
governance that can refuse.

## How it works

```
five apps ──> adapter contract ──> brain (graph + provenance) ──> agent
                                                                   │
                          ActionExecutor — the ONE write choke point
              unknown? forbidden? justified? tainted? stale? gated? ──> act
```

The ordering of those checks is the safety argument. **Taint is evaluated before the
human gate**: if injected content could reach an approval prompt, the attack degrades
into social engineering with extra steps — a plausible-looking request rubber-stamped
by a tired reviewer. The agent refuses rather than delegating that decision.

**The decision path contains no model.** Ingestion, identity resolution, contradiction
detection and action proposal are deterministic Python. A language model may phrase a
customer reply; it is never in the path of a decision about what is true or what may be
written. The run is reproducible, and its misses are inspectable rather than mysterious.

## Verified on this run

| | Claim | Evidence |
|---|---|---|
{rows}

## Numbers

- **Facts ingested:** {self.stats.get('facts_indexed', 0)} across
  {len(self.stats.get('apps', []))} apps ({', '.join(self.stats.get('apps', []))})
- **Graph:** {self.stats.get('node_count', 0)} nodes, {self.stats.get('edge_count', 0)} edges
- **Contradictions surfaced:** {self.conflicts}
- **Identity resolution:** {self.identities}
- **Action ledger:** {self.ledger}

## Test suite

```
{self.tests.strip()}
```

Tests run with **no network and no credentials**. Every adapter — including the fixture
adapter used for demos — is held to the same behavioural conformance suite
(`walnut/conformance.py`), because a `Protocol` constrains signatures only: a
structurally valid adapter can still return uncited evidence or mislabel a
customer-facing write as internal.

## What this does NOT prove

Stated because a reliability brief that only lists successes is not a reliability brief.

- **No live third-party API was called in this run.** Adapters are verified against
  recorded-shape fake transports. Live credentials exercise a different code path, and
  the first live call is where connector bugs surface.
- **Taint detection is a tripwire, not a perimeter.** Pattern matching over adversarial
  text is false-negative-prone by construction. It is safe to rely on only because it
  is not what keeps the system safe: tainted or not, ingested content can never justify
  a state-changing action, so a missed pattern degrades the *explanation* shown to a
  human, not the outcome.
- **Contradiction detection is lexical.** It finds status conflicts on shared, specific
  referents. It does not do semantic entailment and will miss a contradiction phrased
  without status vocabulary.
- **Identity resolution is deterministic, not statistical.** No learned matcher, no
  calibrated threshold. The uncertain band is escalated to a human rather than scored.

## Bugs this build actually found

Recorded because "show how you know it works" should include how you learned it did not.

| Found by | Bug |
|---|---|
| Conformance suite | Slack adapter double-counted thread replies |
| First live demo run | Every recorded decision was being silently discarded — the graph library splats `metadata` as kwargs and `recorded_at` collided with its own parameter, raising inside a bare `except`. The audit trail was writing to nowhere. |
| First live demo run | Contradiction detector reported **303** conflicts on an 88-record corpus: unversioned feature words matched as shared referents and the cartesian product was emitted undeduplicated |
| Demo output review | Deduplication kept the *newest* claim per pair rather than the most *authoritative*, so an all-hands agenda outranked the spec page |
| Demo output review | `regression` matched "regression pass", reading a completed QA issue as broken |
| Console tests | A pasted credential could be echoed back into a rendered page |
"""


def _run_tests() -> str:
    try:
        out = subprocess.run(
            [sys.executable, "-m", "pytest", "-q", "--no-header", "-p", "no:warnings"],
            capture_output=True, text=True, timeout=300,
        )
        lines = [ln for ln in out.stdout.strip().splitlines() if ln.strip()]
        return lines[-1] if lines else "no output"
    except Exception as exc:  # noqa: BLE001
        return f"could not run: {exc}"


def generate(*, run_tests: bool = True) -> Brief:
    """Execute the system end to end and report what actually happened."""
    brief = Brief()
    adapters = load_all_fixtures()
    brain = Brain()
    gate = QueueGate()
    executor = ActionExecutor(adapters, brain, gate, verify_freshness=False)
    agent = WalnutAgent(adapters, brain, executor)

    ingested = agent.ingest(limit=200)
    brief.stats = brain.stats()
    brief.checks.append(Check(
        "Ingests from five independent apps",
        len(brief.stats.get("apps", [])) == 5,
        f"{ingested} records from {len(brief.stats.get('apps', []))} apps",
    ))

    report = agent.resolve_people(load_identities())
    brief.identities = report.summary()
    cross = brief.identities.get("cross_app", 0)
    brief.checks.append(Check(
        "Resolves one human across multiple app identities",
        cross > 0,
        f"{cross} people resolved across more than one app",
    ))
    brief.checks.append(Check(
        "Escalates uncertain identity matches instead of guessing",
        brief.identities.get("needs_human_review", 0) > 0,
        f"{brief.identities.get('needs_human_review', 0)} held for human review",
    ))

    conflicts = detect_contradictions(brain)
    brief.conflicts = len(conflicts)
    brief.checks.append(Check(
        "Surfaces cross-app contradictions",
        bool(conflicts),
        f"{len(conflicts)} found; top subject "
        f"{conflicts[0].subject if conflicts else 'n/a'}",
    ))

    # An unjustified action must be unconstructable.
    try:
        Action(app="slack", operation="post_message", target={}, payload={}, justified_by=())
        unjustifiable = False
    except ValueError:
        unjustifiable = True
    brief.checks.append(Check(
        "An action with no justifying evidence cannot be constructed",
        unjustifiable, "ValueError raised at construction, not at execution",
    ))

    if conflicts:
        plan = [
            {"app": "linear", "operation": "create_issue", "target": {"id": "AUTO-1"},
             "payload": {"title": "Contradiction", "state": "Todo"}, "rationale": "file it"},
            {"app": "github", "operation": "comment", "target": {"id": "pull-288"},
             "payload": {"body": "contradicted"}, "rationale": "tell the engineer"},
            {"app": "slack", "operation": "post_reply", "target": {"id": "s1"},
             "payload": {"text": "confirmed"}, "rationale": "close the loop"},
            {"app": "notion", "operation": "set_property", "target": {"id": "nt001"},
             "payload": {"status": "Disputed"}, "rationale": "repair the stale fact"},
            {"app": "email", "operation": "send_email", "target": {"id": "r1"},
             "payload": {"to": "customer@example.com"}, "rationale": "reply to customer"},
        ]
        results = agent.execute_all(agent.propose_for_conflict(conflicts[0], plan))
        done = [r for r in results if not isinstance(r, Refusal)]
        held = [r for r in results if isinstance(r, Refusal) and r.action.app == "email"]
        brief.checks.append(Check(
            "Executes internal actions across multiple apps",
            len(done) >= 3, f"{len(done)} executed",
        ))
        brief.checks.append(Check(
            "Holds the customer-facing action for a human",
            bool(held) and bool(gate.pending),
            "email.send_email queued for approval; gate fails closed on no answer",
        ))
        if done:
            undone = executor.undo(done[0].action_id)
            brief.checks.append(Check(
                "Every reversible action executed on this run was reversed",
                undone.is_undone, f"{undone.action_id} undone via its own adapter",
            ))
            # The universal claim would be false: send_email cannot be recalled, and
            # the email adapter raises rather than pretending. That is the reason the
            # operation is gated, so assert the pairing instead of the universal.
            from .actions.governance import is_reversible

            irreversible_are_gated = all(
                adapters["email"].capabilities().tier_of(op) >= ActionTier.GATED
                for op in adapters["email"].capabilities().operations
                if not is_reversible("email", op)
            )
            brief.checks.append(Check(
                "Every irreversible operation is gated behind a human",
                irreversible_are_gated,
                "email.send_email cannot be undone, so it cannot execute unapproved",
            ))

    # The refusal — the central claim.
    poisoned = [f for f in brain.by_app("notion")
                if "ignore previous instructions" in f.text.lower()]
    if poisoned:
        refusal = executor.execute(Action(
            app="linear", operation="set_state", target={"id": "X"},
            payload={"state": "Done"}, justified_by=(poisoned[0].node_id,),
            rationale="requested by an ingested document",
        ))
        brief.checks.append(Check(
            "Refuses actions driven by instructions found in ingested content",
            isinstance(refusal, Refusal)
            and refusal.reason.value == "tainted_instruction",
            f"reason={getattr(refusal, 'reason', 'EXECUTED')}; taint path reported",
        ))
        quarantine = executor.execute(Action(
            app="notion", operation="append_block",
            target={"id": poisoned[0].pointer.locator["id"]},
            payload={"text": "[Walnut] contains injected instructions"},
            justified_by=(poisoned[0].node_id,), rationale="quarantine",
        ))
        brief.checks.append(Check(
            "Still permits quarantining the same content",
            not isinstance(quarantine, Refusal),
            "labelling the poison is permitted; acting on it is not",
        ))
    else:
        brief.checks.append(Check(
            "Refuses actions driven by ingested instructions", False,
            "adversarial fixture not found — check fixtures/notion.csv",
        ))

    brief.ledger = executor.ledger.summary()
    brief.tests = _run_tests() if run_tests else "skipped"
    return brief


if __name__ == "__main__":
    b = generate(run_tests="--no-tests" not in sys.argv)
    print(b.render())
    sys.exit(0 if b.all_passed else 1)
